language: node_js
node_js:
  - "8"
  - "9"
  - "10"
addons:
  chrome: stable
# sudo: required
# before_script:
#   - "sudo chown root /opt/google/chrome/chrome-sanbox"
#   - "sudo chmod 4755 /opt/google/chrome/chrome-sanbox"